/* eslint-disable react-hooks/set-state-in-effect */
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { DATA_QUALITY_STATUSES, FINAL_VERDICTS, GROUPS, LONG_TERM_COLUMNS, type LongTermColumn, type LongTermGroup } from "@/lib/longTermColumns";
import { createCsv } from "@/lib/longTermCsv";
import { getLongTermAnalyses, saveLongTermAnalysis } from "@/lib/firestore";

type Cell=string|number|boolean|null|undefined;
type Row=Record<string,Cell|Record<string,string>> & {ticker:string;missingReasons?:Record<string,string>};
type Sort={key:string;dir:"asc"|"desc"};
interface Props{stocks:{ticker:string;company?:string|null;sector?:string|null;industry?:string|null;currentPrice?:number|null}[]}
interface SavedView{name:string;columns:string[];sorts:Sort[];search:string;sector:string;verdict:string;quality:string;filterKey:string;min:string;max:string;custom?:boolean}

const keys=(labels:string[])=>LONG_TERM_COLUMNS.filter(c=>labels.includes(c.label)).map(c=>c.key);
const OVERVIEW=keys(["Ticker","Company","Sector","Current Price","Market Cap","5Y Total-Return CAGR","10Y Total-Return CAGR","Median Rolling 5Y CAGR","Rolling 5Y VOO Win Rate","Maximum Drawdown","Recovery Time (Days)","Net Debt/EBITDA","Forward P/E","FCF Yield","Final Verdict","Data Quality Status"]);
const RETURNS=keys(["Ticker","Company","1Y Total Return","3Y Total-Return CAGR","5Y Total-Return CAGR","10Y Total-Return CAGR","Median Rolling 5Y CAGR","Worst Rolling 5Y CAGR","Rolling 5Y VOO Win Rate","10Y Annualized Excess Return vs VOO","10Y Wealth Multiple","Maximum Drawdown","Maximum-Drawdown Period","Recovery Time (Days)","Longest Underwater Period (Days)","Worst Rolling 12-Month Return","5Y Annualized Volatility","Down-Market Capture vs VOO","Data Quality Status"]);
const FUNDAMENTALS=keys(["Ticker","Company","Gross Margin","Operating Margin","FCF Margin","Net Debt/EBITDA","Net Debt/FCF","Data Quality Status"]);
const VALUATION=keys(["Ticker","Company","Current Price","Trailing P/E","Forward P/E","EV/EBITDA","Price/FCF","FCF Yield","Current P/E vs 5Y Median","Current FCF Yield vs 5Y Median","Base-Case Fair Value","Margin of Safety","Fair-Value Entry Price","Expected 5Y Annualized Return","Final Verdict","Data Quality Status"]);
const RESEARCH=keys(["Ticker","Company","Moat Type","Moat Strength","Moat Trend","Pricing Power","Mission Criticality","Market-Need Durability","Growth Runway","Cyclicality","Disruption Risk","Management Quality","Capital Allocation","Investment Thesis","Key Risks","Thesis Breakers","Personal Notes","Fair-Value Entry Price","Final Verdict","Next Review Date"]);
const RELIABLE=LONG_TERM_COLUMNS.filter(c=>c.source!=="manual"||c.key==="finalVerdict").map(c=>c.key);
const MANUAL_KEYS=new Set(LONG_TERM_COLUMNS.filter(c=>c.source==="manual").map(c=>c.key));
const PRESETS:Record<string,string[]>={"Overview":OVERVIEW,"Returns and Risk":RETURNS,"Fundamentals":FUNDAMENTALS,"Valuation":VALUATION,"Research Notes":RESEARCH,"All Reliable Data":RELIABLE};
const PREF="stock-app-long-term-preferences-v2";
const value=(row:Row,key:string):Cell=>row[key] as Cell;
const hasValue=(v:Cell)=>v!==null&&v!==undefined&&v!==""&&(!(typeof v==="number")||Number.isFinite(v));
const reason=(row:Row,column:LongTermColumn)=>row.missingReasons?.[column.key]??(column.source==="manual"?"Not researched":"Data unavailable");

function display(v:Cell,c:LongTermColumn,row:Row){
  if(!hasValue(v)){if(c.key==="recoveryTime"&&row.recovered===false)return "Not yet recovered";return "—"}
  if(typeof v!=="number")return String(v);
  if(c.format==="percent")return `${(v*100).toFixed(1)}%`;
  if(c.format==="multiple")return `${v.toFixed(2)}x`;
  if(c.format==="currency"){const currency=String(row.currency||"USD");return new Intl.NumberFormat("en-US",{style:"currency",currency,notation:Math.abs(v)>=1e9?"compact":"standard",maximumFractionDigits:2}).format(v)}
  if(c.format==="duration")return `${Math.round(v)} days`;
  return v.toLocaleString(undefined,{maximumFractionDigits:2});
}

export default function LongTermTable({stocks}:Props){
  const [automatic,setAutomatic]=useState<Record<string,Row>>({});
  const [manual,setManual]=useState<Record<string,Row>>({});
  const [loading,setLoading]=useState(false),[error,setError]=useState(""),[partial,setPartial]=useState(false);
  const [view,setView]=useState("Overview"),[visible,setVisible]=useState(OVERVIEW),[order,setOrder]=useState(LONG_TERM_COLUMNS.map(c=>c.key));
  const [sorts,setSorts]=useState<Sort[]>([]),[search,setSearch]=useState(""),[sector,setSector]=useState(""),[verdict,setVerdict]=useState(""),[quality,setQuality]=useState("");
  const [filterKey,setFilterKey]=useState("totalReturnCagr5y"),[min,setMin]=useState(""),[max,setMax]=useState("");
  const [density,setDensity]=useState<"comfortable"|"compact"|"dense">("compact"),[collapsed,setCollapsed]=useState<Set<LongTermGroup>>(new Set()),[selected,setSelected]=useState<Set<string>>(new Set());
  const [page,setPage]=useState(1),[fullscreen,setFullscreen]=useState(false),[controls,setControls]=useState(false),[hideEmptyColumns,setHideEmptyColumns]=useState(true),[hideInsufficient,setHideInsufficient]=useState(false);
  const [saved,setSaved]=useState<Record<string,SavedView>>({}),[editor,setEditor]=useState<{ticker:string;column:LongTermColumn;value:string}|null>(null),[widths,setWidths]=useState<Record<string,number>>({});
  const root=useRef<HTMLDivElement>(null),skipFirstPreferenceWrite=useRef(true);

  useEffect(()=>{try{const p=JSON.parse(localStorage.getItem(PREF)||"{}");if(p.order)setOrder(p.order);if(p.density)setDensity(p.density);if(p.saved)setSaved(p.saved);if(p.hideEmptyColumns!=null)setHideEmptyColumns(p.hideEmptyColumns)}catch{}},[]);
  useEffect(()=>{if(skipFirstPreferenceWrite.current){skipFirstPreferenceWrite.current=false;return}localStorage.setItem(PREF,JSON.stringify({order,density,saved,hideEmptyColumns}));},[order,density,saved,hideEmptyColumns]);
  useEffect(()=>{getLongTermAnalyses().then(x=>setManual(x as Record<string,Row>)).catch(()=>setError("Manual analysis could not be loaded."))},[]);
  const refresh=async()=>{setLoading(true);setError("");try{const res=await fetch(`/api/long-term?tickers=${stocks.slice(0,100).map(s=>s.ticker).join(",")}`),body=await res.json();if(!res.ok)throw new Error(body.error||"Refresh failed");setAutomatic(body.data||{});setPartial(Boolean(body.partial))}catch(e){setError(e instanceof Error?e.message:"Market data unavailable")}finally{setLoading(false)}};
  useEffect(()=>{if(stocks.length)void refresh()},[stocks.length]); // eslint-disable-line react-hooks/exhaustive-deps

  const rows=useMemo(()=>stocks.map(base=>{const saved=manual[base.ticker]??({ticker:base.ticker} as Row),manualFields=Object.fromEntries(Object.entries(saved).filter(([key])=>MANUAL_KEYS.has(key)));return {...base,...automatic[base.ticker],...manualFields,ticker:base.ticker,finalVerdict:manualFields.finalVerdict||"Not Yet Researched",missingReasons:automatic[base.ticker]?.missingReasons as Record<string,string>|undefined} as Row}),[stocks,automatic,manual]);
  const sectors=useMemo(()=>[...new Set(rows.map(r=>String(r.sector||"")).filter(Boolean))].sort(),[rows]);
  const filtered=useMemo(()=>{const query=search.toLowerCase();return rows.filter(r=>{const metric=value(r,filterKey);return(!query||`${r.ticker} ${r.company||""}`.toLowerCase().includes(query))&&(!sector||r.sector===sector)&&(!verdict||r.finalVerdict===verdict)&&(!quality||r.dataQualityStatus===quality)&&(!hideInsufficient||r.dataQualityStatus!=="Insufficient Data")&&(!min||(hasValue(metric)&&Number(metric)>=+min))&&(!max||(hasValue(metric)&&Number(metric)<=+max))}).sort((a,b)=>{for(const s of sorts){const cmp=compare(value(a,s.key),value(b,s.key));if(cmp)return s.dir==="asc"?cmp:-cmp}return 0})},[rows,search,sector,verdict,quality,hideInsufficient,min,max,filterKey,sorts]);
  const shownCols=order.map(k=>LONG_TERM_COLUMNS.find(c=>c.key===k)).filter((c):c is LongTermColumn=>Boolean(c&&visible.includes(c.key)&&!collapsed.has(c.group)&&(!hideEmptyColumns||c.key==="ticker"||c.key==="company"||filtered.some(r=>hasValue(value(r,c.key))))));
  const pageSize=50,pages=Math.max(1,Math.ceil(filtered.length/pageSize)),paged=filtered.slice((page-1)*pageSize,page*pageSize);
  useEffect(()=>setPage(1),[search,sector,verdict,quality,hideInsufficient,min,max,view]);

  const chooseView=(name:string)=>{const custom=saved[name];setView(name);setVisible(custom?.columns??PRESETS[name]??OVERVIEW);if(custom){setSorts(custom.sorts);setSearch(custom.search);setSector(custom.sector);setVerdict(custom.verdict);setQuality(custom.quality??"");setFilterKey(custom.filterKey);setMin(custom.min);setMax(custom.max)}};
  const edit=async(ticker:string,key:string,next:Cell)=>{setManual(p=>({...p,[ticker]:{...(p[ticker]||{ticker}),[key]:next}}));try{await saveLongTermAnalysis(ticker,{[key]:next})}catch{setError(`Could not save ${ticker}.`)}};
  const sort=(key:string,add:boolean)=>setSorts(p=>{const old=p.find(x=>x.key===key),next:Sort={key,dir:old?.dir==="asc"?"desc":"asc"};return add?[...p.filter(x=>x.key!==key),next]:[next]});

  const exportCsv=(scope:"view"|"visible"|"selected"|"reliable"|"research")=>{
    const requested=scope==="reliable"?RELIABLE.filter(k=>LONG_TERM_COLUMNS.find(c=>c.key===k)?.quantitative||["ticker","company","currency","dataLastUpdated"].includes(k)):scope==="research"?RESEARCH:scope==="view"?(saved[view]?.columns??PRESETS[view]??visible):shownCols.map(c=>c.key);
    const exportRows=scope==="selected"?filtered.filter(r=>selected.has(r.ticker)):filtered;
    const columns=requested.map(k=>LONG_TERM_COLUMNS.find(c=>c.key===k)).filter((c):c is LongTermColumn=>Boolean(c&&(c.key==="ticker"||c.key==="company"||exportRows.some(r=>hasValue(value(r,c.key))))));
    const headers:string[]=[],getters:((r:Row)=>unknown)[]=[];
    for(const c of columns){headers.push(c.label);getters.push(r=>hasValue(value(r,c.key))?value(r,c.key):reason(r,c));if(c.quantitative){headers.push(`${c.label} Status`,`${c.label} Source`,`${c.label} Period`);getters.push(r=>hasValue(value(r,c.key))?"Available":reason(r,c),()=>sourceLabel(c),()=>c.period)}}
    if(!columns.some(c=>c.key==="dataLastUpdated")){headers.push("Data Last Updated");getters.push(r=>value(r,"dataLastUpdated")??"Data unavailable")}
    download(createCsv(headers,exportRows.map(r=>getters.map(get=>get(r)))),`long-term-${scope}-${new Date().toISOString().slice(0,10)}.csv`);
  };

  const pad=density==="dense"?"px-2 py-1":density==="compact"?"px-2.5 py-1.5":"px-3 py-2.5";
  return <div ref={root} className={`${fullscreen?"fixed inset-0 z-50 bg-[var(--background)] p-4":""} space-y-3`}>
    <div className="surface-card p-4 space-y-4">
      <div className="flex flex-wrap gap-2 items-center"><div className="mr-3"><strong className="block text-sm text-gray-900">Long Term Comparison</strong><span className="text-xs text-gray-500">Validated market data and focused manual research</span></div><select aria-label="Saved view" className="input-field" value={view} onChange={e=>chooseView(e.target.value)}>{[...Object.keys(PRESETS),...Object.keys(saved)].map(x=><option key={x}>{x}</option>)}</select><input className="input-field min-w-48" placeholder="Search ticker or company" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Sector" className="input-field" value={sector} onChange={e=>setSector(e.target.value)}><option value="">All sectors</option>{sectors.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Final verdict" className="input-field" value={verdict} onChange={e=>setVerdict(e.target.value)}><option value="">All verdicts</option>{FINAL_VERDICTS.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Data quality" className="input-field" value={quality} onChange={e=>setQuality(e.target.value)}><option value="">All data quality</option>{DATA_QUALITY_STATUSES.map(x=><option key={x}>{x}</option>)}</select><button className="btn btn-secondary" onClick={()=>setControls(!controls)}>{controls?"Hide columns & filters":"Columns & filters"}</button><button className="btn btn-ghost" onClick={refresh} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button><button className="btn btn-ghost" onClick={()=>{setFullscreen(!fullscreen);setTimeout(()=>fullscreen?document.exitFullscreen?.():root.current?.requestFullscreen?.().catch(()=>{}),0)}}>{fullscreen?"Exit full screen":"Full screen"}</button></div>
      {controls&&<div className="border-t border-[var(--border)] pt-4 space-y-4"><div className="flex flex-wrap gap-2 items-center"><select aria-label="Numeric filter" className="input-field" value={filterKey} onChange={e=>setFilterKey(e.target.value)}>{LONG_TERM_COLUMNS.filter(c=>c.quantitative).map(c=><option value={c.key} key={c.key}>{c.label}</option>)}</select><input className="input-field w-28" type="number" placeholder="Minimum" value={min} onChange={e=>setMin(e.target.value)}/><input className="input-field w-28" type="number" placeholder="Maximum" value={max} onChange={e=>setMax(e.target.value)}/><select aria-label="Table density" className="input-field" value={density} onChange={e=>setDensity(e.target.value as typeof density)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option><option value="dense">Dense</option></select><label className="flex items-center gap-2 text-xs text-gray-600"><input className="accent-[var(--accent)]" type="checkbox" checked={hideEmptyColumns} onChange={e=>setHideEmptyColumns(e.target.checked)}/>Hide columns with no data</label><label className="flex items-center gap-2 text-xs text-gray-600"><input className="accent-[var(--accent)]" type="checkbox" checked={hideInsufficient} onChange={e=>setHideInsufficient(e.target.checked)}/>Hide insufficient-data stocks</label><button className="btn btn-ghost" onClick={()=>{const name=prompt("Saved view name");if(name)setSaved(p=>({...p,[name]:{name,columns:visible,sorts,search,sector,verdict,quality,filterKey,min,max,custom:true}}))}}>Save custom view</button>{saved[view]&&<button className="btn btn-ghost text-red-600" onClick={()=>setSaved(p=>{const n={...p};delete n[view];chooseView("Overview");return n})}>Delete view</button>}</div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-x-4 gap-y-2 max-h-52 overflow-auto rounded-lg bg-gray-50/70 border border-gray-100 p-3">{order.map((k,i)=>{const c=LONG_TERM_COLUMNS.find(x=>x.key===k);if(!c)return null;return <label draggable onDragStart={e=>e.dataTransfer.setData("text/plain",String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{const from=+e.dataTransfer.getData("text/plain");setOrder(p=>{const n=[...p],v=n.splice(from,1)[0];n.splice(i,0,v);return n})}} key={k} className="text-xs text-gray-700 flex gap-2 items-center cursor-move"><input className="accent-[var(--accent)]" type="checkbox" checked={visible.includes(k)} onChange={()=>setVisible(p=>p.includes(k)?p.filter(x=>x!==k):[...p,k])}/><span>{c.label}</span><small className="ml-auto text-gray-400">{c.source}</small></label>})}</div></div>}
      <div className="flex flex-wrap gap-2 items-center text-xs">{GROUPS.map(g=><button key={g} className={`rounded-full px-2.5 py-1 border font-medium ${collapsed.has(g)?"bg-white border-[var(--border)] text-gray-500":"bg-[var(--accent-soft)] border-indigo-100 text-[var(--accent-soft-text)]"}`} onClick={()=>setCollapsed(p=>toggleSet(p,g))}>{collapsed.has(g)?"+":"−"} {g}</button>)}<span className="ml-auto text-gray-500">{filtered.length} rows · Shift-click headers for multi-sort</span><select aria-label="Export CSV" className="input-field" onChange={e=>{if(e.target.value){exportCsv(e.target.value as Parameters<typeof exportCsv>[0]);e.target.value=""}}} defaultValue=""><option value="">Export CSV…</option><option value="view">Current view</option><option value="visible">Visible rows and columns</option><option value="selected">Selected rows</option><option value="reliable">All reliable quantitative fields</option><option value="research">Research notes</option></select></div>
    </div>
    {error&&<div className="p-3 rounded-lg border border-red-200 bg-red-50 text-sm text-red-700">{error}</div>}{partial&&<div className="p-3 rounded-lg border border-amber-200 bg-amber-50 text-sm text-amber-800">Partial data: some symbols could not be refreshed. Manual data remain available.</div>}{!loading&&!error&&rows.length===0&&<div className="surface-card p-8 text-center text-sm text-gray-500">No stocks available.</div>}
    <div className={`overflow-auto border border-gray-200 rounded-lg bg-white ${fullscreen?"max-h-[calc(100vh-13rem)]":"max-h-[72vh]"}`}><table className="min-w-full text-xs border-separate border-spacing-0"><thead className="sticky top-0 z-30"><tr>{groupSpans(shownCols).map(x=><th key={x.group} colSpan={x.span} className="bg-indigo-50 text-indigo-700 border-b border-r border-indigo-100 px-3 py-1.5 text-left text-[10px] font-bold uppercase tracking-wider whitespace-nowrap">{x.group}</th>)}</tr><tr>{shownCols.map(c=><th key={c.key} title={`${c.description}\nSource: ${sourceLabel(c)}\nPeriod: ${c.period}`} onClick={e=>sort(c.key,e.shiftKey)} style={{width:widths[c.key]||160,minWidth:widths[c.key]||160,maxWidth:widths[c.key]||160,left:stickyLeft(c.key,shownCols,widths)}} className={`${pad} overflow-hidden bg-gray-100 border-b border-r border-gray-200 text-left text-xs font-semibold text-gray-500 uppercase tracking-wide whitespace-nowrap cursor-pointer hover:text-gray-900 ${c.key==="ticker"||c.key==="company"?"sticky z-40":""}`}>{c.label}{sorts.findIndex(s=>s.key===c.key)>=0?` ${sorts.findIndex(s=>s.key===c.key)+1}${sorts.find(s=>s.key===c.key)?.dir==="asc"?"↑":"↓"}`:""}<span className="float-right cursor-col-resize px-1 text-gray-300 hover:text-gray-500" onMouseDown={e=>resize(e,c.key,widths,setWidths)}>⋮</span></th>)}</tr></thead><tbody>{paged.map(r=><tr key={r.ticker} className="group">{shownCols.map(c=>{const v=value(r,c.key),sticky=c.key==="ticker"||c.key==="company",missing=!hasValue(v),tooltip=c.key==="dataQualityStatus"||c.key==="missingKeyMetrics"?String(r.missingDetail||"No missing key metrics"):missing?reason(r,c):display(v,c,r);return <td key={c.key} style={{left:stickyLeft(c.key,shownCols,widths),width:widths[c.key]||160,minWidth:widths[c.key]||160,maxWidth:widths[c.key]||160}} className={`${pad} overflow-hidden text-ellipsis whitespace-nowrap border-b border-r border-gray-100 bg-white transition-colors group-hover:bg-gray-50 ${missing?"text-gray-400":"text-gray-700"} ${sticky?"sticky z-20":""}`} title={tooltip}>{c.key==="ticker"&&<input className="mr-2 accent-[var(--accent)]" type="checkbox" checked={selected.has(r.ticker)} onChange={()=>setSelected(p=>toggleSet(p,r.ticker))}/>} {c.editable?<Editable value={v} column={c} onChange={next=>c.format==="longtext"?setEditor({ticker:r.ticker,column:c,value:String(v||"")}):edit(r.ticker,c.key,next)}/>:display(v,c,r)}</td>})}</tr>)}</tbody></table></div>
    <div className="flex justify-between items-center"><span className="text-xs text-gray-500">Page {page} of {pages}</span><div className="flex gap-2"><button className="btn btn-ghost" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="btn btn-ghost" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>
    {editor&&<div className="fixed inset-0 z-[70] bg-black/40 flex items-center justify-center p-4"><div className="surface-card p-5 w-full max-w-2xl"><h3 className="font-semibold mb-3">{editor.ticker} — {editor.column.label}</h3><textarea autoFocus className="input-field w-full min-h-56 resize-y" value={editor.value} onChange={e=>setEditor({...editor,value:e.target.value})}/><div className="flex justify-end gap-2 mt-3"><button className="btn btn-ghost" onClick={()=>setEditor(null)}>Cancel</button><button className="btn btn-primary" onClick={()=>{void edit(editor.ticker,editor.column.key,editor.value);setEditor(null)}}>Save</button></div></div></div>}
  </div>;
}

function Editable({value,column,onChange}:{value:Cell;column:LongTermColumn;onChange:(v:Cell)=>void}){if(column.format==="longtext")return <button className="text-[var(--accent)] underline" onClick={()=>onChange(value)}>{value?"Edit":"Add"}</button>;if(column.options)return <select className="bg-transparent min-w-28" value={value==null?"":String(value)} onChange={e=>onChange(e.target.value||null)}><option value="">{column.key==="finalVerdict"?"Not Yet Researched":"Not researched"}</option>{column.options.map(x=><option key={x}>{x}</option>)}</select>;const numeric=["percent","multiple","currency","number","duration"].includes(column.format);return <input className="bg-transparent border-b border-dashed w-28" type={numeric?"number":column.format==="date"?"date":"text"} step="any" value={value==null?"":String(value)} placeholder="Not researched" onChange={e=>onChange(numeric?(e.target.value===""?null:Number(e.target.value)):e.target.value)}/>}
function compare(a:Cell,b:Cell){if(!hasValue(a)&&!hasValue(b))return 0;if(!hasValue(a))return 1;if(!hasValue(b))return-1;return typeof a==="number"&&typeof b==="number"?a-b:String(a).localeCompare(String(b))}
function groupSpans(cols:LongTermColumn[]){const out:{group:string;span:number}[]=[];for(const c of cols){const last=out.at(-1);if(last?.group===c.group)last.span++;else out.push({group:c.group,span:1})}return out}
function toggleSet<T>(current:Set<T>,item:T){const next=new Set(current);if(next.has(item))next.delete(item);else next.add(item);return next}
function stickyLeft(key:string,cols:LongTermColumn[],widths:Record<string,number>){if(key==="ticker")return 0;if(key==="company")return cols.some(c=>c.key==="ticker")?(widths.ticker||160):0;return undefined}
function resize(e:React.MouseEvent,key:string,widths:Record<string,number>,setWidths:React.Dispatch<React.SetStateAction<Record<string,number>>>){e.stopPropagation();const start=e.clientX,w=widths[key]||160;const move=(m:MouseEvent)=>setWidths(p=>({...p,[key]:Math.max(80,w+m.clientX-start)}));const up=()=>{window.removeEventListener("mousemove",move);window.removeEventListener("mouseup",up)};window.addEventListener("mousemove",move);window.addEventListener("mouseup",up)}
function download(csv:string,name:string){const a=document.createElement("a"),url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function sourceLabel(column:LongTermColumn){return column.source==="sourced"?"Yahoo Finance":column.source==="calculated"?"Calculated from Yahoo Finance data":"Manual"}
