/* eslint-disable react-hooks/set-state-in-effect, @typescript-eslint/no-unused-expressions */
"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { LONG_TERM_COLUMNS, GROUPS, type LongTermColumn, type LongTermGroup } from "@/lib/longTermColumns";
import { expectedReturn, SCORE_WEIGHTS } from "@/lib/longTermCalculations";
import { getLongTermAnalyses, saveLongTermAnalysis } from "@/lib/firestore";

type Cell = string | number | boolean | null | undefined;
type Row = Record<string, Cell> & { ticker: string };
type Sort = {key:string;dir:"asc"|"desc"};
interface Props { stocks:{ticker:string;company?:string|null;sector?:string|null;industry?:string|null;currentPrice?:number|null}[] }
interface SavedView {name:string;columns:string[];sorts:Sort[];search:string;sector:string;verdict:string;filterKey:string;min:string;max:string;custom?:boolean}

const keys=(labels:string[])=>LONG_TERM_COLUMNS.filter(c=>labels.includes(c.label)).map(c=>c.key);
const groupKeys=(...groups:LongTermGroup[])=>LONG_TERM_COLUMNS.filter(c=>groups.includes(c.group)).map(c=>c.key);
const OVERVIEW=keys(["Ticker","Company","Sector","Current Price","Market Cap","10Y Total-Return CAGR","Median Rolling 5Y CAGR","Maximum Drawdown","5Y Revenue CAGR","5Y EPS CAGR","5Y FCF per Share CAGR","5Y Median ROIC","Forward P/E","FCF Yield","Expected 5Y Annualized Return","Compounder Score","Final Verdict"]);
const PRESETS:Record<string,string[]>={Overview:OVERVIEW,Returns:groupKeys("Company","Historical Returns"),Risk:groupKeys("Company","Risk and Drawdowns"),Fundamentals:groupKeys("Company","Business Compounding","Financial Resilience"),Valuation:groupKeys("Company","Valuation","Expected Return"),Qualitative:groupKeys("Company","Qualitative Analysis"),Portfolio:keys(["Ticker","Company","Suggested Verdict","Final Verdict","Position Status","Current Portfolio Weight","Target Portfolio Weight","Fair-Value Entry Price","Expected 5Y Annualized Return","Next Review Date","Review Status"]),"All Columns":LONG_TERM_COLUMNS.map(c=>c.key)};
const PREF="stock-app-long-term-preferences-v1";
const verdicts=["Attractive Now","Accumulate Gradually","Watchlist","Hold","Too Expensive","Quality Concerns","Avoid"];

function scoreRow(r:Row){
  const avg=(values:Cell[])=>{const n=values.map(Number).filter(Number.isFinite);return n.length?n.reduce((a,b)=>a+b,0)/n.length*20:null};
  const categories={
    businessQualityScore:avg([r.moatStrength,r.recurringRevenueStrength,r.pricingPower,r.missionCriticality,r.marketNeedDurability,r.growthRunway]),
    fundamentalCompoundingScore:avg([r.revenueCagr5y==null?null:Math.max(1,Math.min(5,Number(r.revenueCagr5y)*20)),r.epsCagr5y==null?null:Math.max(1,Math.min(5,Number(r.epsCagr5y)*20)),r.fcfPerShareCagr5y==null?null:Math.max(1,Math.min(5,Number(r.fcfPerShareCagr5y)*20))]),
    financialResilienceScore:r.balanceSheetScore==null?null:Number(r.balanceSheetScore),
    historicalReturnQualityScore:avg([r.totalReturnCagr10y==null?null:Math.max(1,Math.min(5,Number(r.totalReturnCagr10y)*20)),r.positiveRolling5yRate==null?null:Number(r.positiveRolling5yRate)*5]),
    valuationScore:avg([r.expectedReturn5y==null?null:Math.max(1,Math.min(5,Number(r.expectedReturn5y)*20)),r.marginOfSafety==null?null:Math.max(1,Math.min(5,3+Number(r.marginOfSafety)*5))]),
    managementCapitalAllocationScore:avg([r.managementQuality,r.capitalAllocation]),
  };
  const map: [keyof typeof categories, keyof typeof SCORE_WEIGHTS][]=[["businessQualityScore","businessQualityScore"],["fundamentalCompoundingScore","fundamentalCompoundingScore"],["financialResilienceScore","financialResilienceScore"],["historicalReturnQualityScore","historicalReturnQualityScore"],["valuationScore","valuationScore"],["managementCapitalAllocationScore","managementCapitalAllocationScore"]];
  const available=map.filter(([k])=>categories[k]!=null), weight=available.reduce((s,[,w])=>s+SCORE_WEIGHTS[w],0), compounderScore=weight?available.reduce((s,[k,w])=>s+Number(categories[k])*SCORE_WEIGHTS[w],0)/weight:null;
  return {...categories,compounderScore,scoreComplete:available.length===map.length,scoreDetail:map.map(([k,w])=>`${k.replace(/Score$/,"")}: ${categories[k]?.toFixed(1)??"missing"} × ${(SCORE_WEIGHTS[w]*100).toFixed(0)}%`).join("\n")+`\n${available.length===map.length?"Full weighted score":"Incomplete — weights rebalanced across available categories"}`};
}

function display(v:Cell,c:LongTermColumn,row:Row){
  if(v==null||v==="")return "N/A";
  if(c.key==="recoveryTime"&&row.recovered===false)return "Not yet recovered";
  if(typeof v!=="number")return String(v);
  if(c.format==="percent")return `${(v*100).toFixed(1)}%`;
  if(c.format==="multiple")return `${v.toFixed(2)}x`;
  if(c.format==="currency"){const currency=String(row.currency||"USD");return new Intl.NumberFormat("en-US",{style:"currency",currency,notation:Math.abs(v)>=1e9?"compact":"standard",maximumFractionDigits:2}).format(v)}
  if(c.format==="score")return v.toFixed(1);
  if(c.format==="duration")return `${Math.round(v)} days`;
  return v.toLocaleString(undefined,{maximumFractionDigits:2});
}

export default function LongTermTable({stocks}:Props){
  const [automatic,setAutomatic]=useState<Record<string,Row>>({}),[manual,setManual]=useState<Record<string,Row>>({}),[loading,setLoading]=useState(false),[error,setError]=useState(""),[partial,setPartial]=useState(false);
  const [view,setView]=useState("Overview"),[visible,setVisible]=useState(OVERVIEW),[order,setOrder]=useState(LONG_TERM_COLUMNS.map(c=>c.key)),[sorts,setSorts]=useState<Sort[]>([]),[search,setSearch]=useState(""),[sector,setSector]=useState(""),[verdict,setVerdict]=useState(""),[filterKey,setFilterKey]=useState("compounderScore"),[min,setMin]=useState(""),[max,setMax]=useState(""),[density,setDensity]=useState<"comfortable"|"compact"|"dense">("compact"),[collapsed,setCollapsed]=useState<Set<LongTermGroup>>(new Set()),[selected,setSelected]=useState<Set<string>>(new Set()),[page,setPage]=useState(1),[fullscreen,setFullscreen]=useState(false),[controls,setControls]=useState(false),[saved,setSaved]=useState<Record<string,SavedView>>({}),[editor,setEditor]=useState<{ticker:string;column:LongTermColumn;value:string}|null>(null),[widths,setWidths]=useState<Record<string,number>>({});
  const root=useRef<HTMLDivElement>(null), skipFirstPreferenceWrite=useRef(true);
  useEffect(()=>{try{const p=JSON.parse(localStorage.getItem(PREF)||"{}");if(p.order)setOrder(p.order);if(p.density)setDensity(p.density);if(p.saved)setSaved(p.saved);if(p.defaultView&&PRESETS[p.defaultView]){setView(p.defaultView);setVisible(PRESETS[p.defaultView]);}}catch{}},[]);
  useEffect(()=>{if(skipFirstPreferenceWrite.current){skipFirstPreferenceWrite.current=false;return}localStorage.setItem(PREF,JSON.stringify({order,density,saved,defaultView:view}));},[order,density,saved,view]);
  useEffect(()=>{getLongTermAnalyses().then(x=>setManual(x as Record<string,Row>)).catch(()=>setError("Manual analysis could not be loaded."));},[]);
  const refresh=async()=>{setLoading(true);setError("");try{const res=await fetch(`/api/long-term?tickers=${stocks.slice(0,100).map(s=>s.ticker).join(",")}`);const body=await res.json();if(!res.ok)throw new Error(body.error||"Refresh failed");setAutomatic(body.data||{});setPartial(Boolean(body.partial));}catch(e){setError(e instanceof Error?e.message:"Market data unavailable")}finally{setLoading(false)}};
  useEffect(()=>{if(stocks.length)refresh();},[stocks.length]); // eslint-disable-line react-hooks/exhaustive-deps
  const rows=useMemo(()=>stocks.map(base=>{let r:Row={...base,...automatic[base.ticker],...manual[base.ticker],ticker:base.ticker};const er=expectedReturn(num(r.expectedFundamentalGrowth),num(r.dividendYield),num(r.netBuybackYield),num(r.currentValuationMultiple)||num(r.forwardPe),num(r.expectedYear5ValuationMultiple));r={...r,fundamentalGrowthContribution:er.fundamentalGrowthContribution,expectedDividendContribution:er.dividendContribution,buybackDilutionContribution:er.buybackContribution,valuationChangeContribution:er.valuationChangeContribution,expectedReturn5y:er.expectedAnnualizedReturn};if(num(r.fairValueEntryPrice)!=null){r.baseCaseFairValue=r.fairValueEntryPrice;r.marginOfSafety=num(r.currentPrice)&&num(r.fairValueEntryPrice)?num(r.fairValueEntryPrice)!/num(r.currentPrice)!-1:null}const scores=scoreRow(r);r={...r,...scores};r.suggestedVerdict=suggest(r);return r;}),[stocks,automatic,manual]);
  const sectors=useMemo(()=>[...new Set(rows.map(r=>String(r.sector||"")).filter(Boolean))].sort(),[rows]);
  const shownCols=order.map(k=>LONG_TERM_COLUMNS.find(c=>c.key===k)).filter((c):c is LongTermColumn=>Boolean(c&&visible.includes(c.key)&&!collapsed.has(c.group)));
  const filtered=useMemo(()=>{const q=search.toLowerCase();return rows.filter(r=>(!q||`${r.ticker} ${r.company||""}`.toLowerCase().includes(q))&&(!sector||r.sector===sector)&&(!verdict||r.finalVerdict===verdict||r.suggestedVerdict===verdict)&&(!min||num(r[filterKey])!>=+min)&&(!max||num(r[filterKey])!<=+max)).sort((a,b)=>{for(const s of sorts){const av=a[s.key],bv=b[s.key];const cmp=compare(av,bv);if(cmp)return s.dir==="asc"?cmp:-cmp}return 0})},[rows,search,sector,verdict,min,max,filterKey,sorts]);
  const pageSize=50,pages=Math.max(1,Math.ceil(filtered.length/pageSize)),paged=filtered.slice((page-1)*pageSize,page*pageSize);useEffect(()=>setPage(1),[search,sector,verdict,min,max,view]);
  const chooseView=(name:string)=>{const v=saved[name];setView(name);setVisible(v?.columns??PRESETS[name]??OVERVIEW);if(v){setSorts(v.sorts);setSearch(v.search);setSector(v.sector);setVerdict(v.verdict);setFilterKey(v.filterKey);setMin(v.min);setMax(v.max)}};
  const edit=async(ticker:string,key:string,value:Cell)=>{setManual(p=>({...p,[ticker]:{...(p[ticker]||{ticker}),[key]:value}}));try{await saveLongTermAnalysis(ticker,{[key]:value})}catch{setError(`Could not save ${ticker}.`)} };
  const exportCsv=(scope:"visible"|"selected"|"view"|"all")=>{const selectedKeys=scope==="all"?LONG_TERM_COLUMNS.map(c=>c.key):scope==="view"?(saved[view]?.columns??PRESETS[view]??visible):shownCols.map(c=>c.key);const cols=selectedKeys.map(k=>LONG_TERM_COLUMNS.find(c=>c.key===k)).filter((c):c is LongTermColumn=>Boolean(c));const rr=scope==="selected"?filtered.filter(r=>selected.has(r.ticker)):scope==="all"?rows:filtered;const esc=(v:Cell)=>{if(v==null||v==="")return "N/A";const s=String(v);return /[",\r\n]/.test(s)?`"${s.replace(/"/g,'""')}"`:s};const csv="\uFEFF"+[cols.map(c=>esc(c.label)).join(","),...rr.map(r=>cols.map(c=>esc(r[c.key])).join(","))].join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download=`long-term-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href)};
  const sort=(key:string,add:boolean)=>setSorts(p=>{const old=p.find(x=>x.key===key),next:{key:string;dir:"asc"|"desc"}={key,dir:old?.dir==="asc"?"desc":"asc"};return add?[...p.filter(x=>x.key!==key),next]:[next]});
  const pad=density==="dense"?"px-2 py-1":density==="compact"?"px-2.5 py-1.5":"px-3 py-2.5";
  return <div ref={root} className={`${fullscreen?"fixed inset-0 z-50 bg-white p-3":""} space-y-3`}>
    <div className="surface-card p-3 space-y-3"><div className="flex flex-wrap gap-2 items-center"><strong className="mr-2">Long Term Comparison</strong><select className="input" value={view} onChange={e=>chooseView(e.target.value)}>{[...Object.keys(PRESETS),...Object.keys(saved)].map(x=><option key={x}>{x}</option>)}</select><input className="input min-w-48" placeholder="Search ticker or company" value={search} onChange={e=>setSearch(e.target.value)}/><select className="input" value={sector} onChange={e=>setSector(e.target.value)}><option value="">All sectors</option>{sectors.map(x=><option key={x}>{x}</option>)}</select><select className="input" value={verdict} onChange={e=>setVerdict(e.target.value)}><option value="">All verdicts</option>{verdicts.map(x=><option key={x}>{x}</option>)}</select><button className="btn btn-ghost" onClick={()=>setControls(!controls)}>Columns & filters</button><button className="btn btn-ghost" onClick={refresh} disabled={loading}>{loading?"Refreshing…":"Refresh"}</button><button className="btn btn-ghost" onClick={()=>{setFullscreen(!fullscreen);setTimeout(()=>fullscreen?document.exitFullscreen?.():root.current?.requestFullscreen?.().catch(()=>{}),0)}}>{fullscreen?"Exit full screen":"Full screen"}</button></div>
    {controls&&<div className="border-t pt-3 space-y-3"><div className="flex flex-wrap gap-2"><select className="input" value={filterKey} onChange={e=>setFilterKey(e.target.value)}>{LONG_TERM_COLUMNS.filter(c=>["number","percent","multiple","currency","score","duration"].includes(c.format)).map(c=><option value={c.key} key={c.key}>{c.label}</option>)}</select><input className="input w-28" type="number" placeholder="Minimum" value={min} onChange={e=>setMin(e.target.value)}/><input className="input w-28" type="number" placeholder="Maximum" value={max} onChange={e=>setMax(e.target.value)}/><select className="input" value={density} onChange={e=>setDensity(e.target.value as typeof density)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option><option value="dense">Dense</option></select><button className="btn btn-ghost" onClick={()=>{const name=prompt("Saved view name");if(name)setSaved(p=>({...p,[name]:{name,columns:visible,sorts,search,sector,verdict,filterKey,min,max,custom:true}}))}}>Save custom view</button>{saved[view]&&<><button className="btn btn-ghost" onClick={()=>{const name=prompt("Rename view",view);if(name)setSaved(p=>{const n={...p,[name]:{...p[view],name}};delete n[view];setView(name);return n})}}>Rename</button><button className="btn btn-ghost text-red-600" onClick={()=>setSaved(p=>{const n={...p};delete n[view];chooseView("Overview");return n})}>Delete</button></>}</div><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-1 max-h-52 overflow-auto">{order.map((k,i)=>{const c=LONG_TERM_COLUMNS.find(x=>x.key===k)!;return <label draggable onDragStart={e=>e.dataTransfer.setData("text/plain",String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>{const from=+e.dataTransfer.getData("text/plain");setOrder(p=>{const n=[...p],v=n.splice(from,1)[0];n.splice(i,0,v);return n})}} key={k} className="text-xs flex gap-2 items-center cursor-move"><input type="checkbox" checked={visible.includes(k)} onChange={()=>setVisible(p=>p.includes(k)?p.filter(x=>x!==k):[...p,k])}/>{c.label}<small className="text-gray-400">{c.source}</small></label>})}</div></div>}
    <div className="flex flex-wrap gap-2 items-center text-xs">{GROUPS.map(g=><button key={g} className={`rounded px-2 py-1 border ${collapsed.has(g)?"bg-gray-100":"bg-blue-50 text-blue-700"}`} onClick={()=>setCollapsed(p=>{const n=new Set(p);n.has(g)?n.delete(g):n.add(g);return n})}>{collapsed.has(g)?"+":"−"} {g}</button>)}<span className="ml-auto">{filtered.length} rows · Shift-click headers for multi-sort</span><select className="input" onChange={e=>{if(e.target.value)exportCsv(e.target.value as "visible")}} defaultValue=""><option value="">Export CSV…</option><option value="visible">Visible rows & columns</option><option value="selected">Selected rows</option><option value="view">Current saved view</option><option value="all">All rows & columns</option></select></div></div>
    {error&&<div className="p-3 rounded bg-red-50 text-red-700">{error}</div>}{partial&&<div className="p-3 rounded bg-amber-50 text-amber-800">Partial data: some symbols could not be refreshed. Existing/manual data remain available.</div>}{!loading&&!error&&rows.length===0&&<div className="p-8 text-center text-gray-500">No stocks available.</div>}
    <div className={`overflow-auto border rounded-lg ${fullscreen?"max-h-[calc(100vh-12rem)]":"max-h-[72vh]"}`}><table className="text-xs border-separate border-spacing-0"><thead className="sticky top-0 z-30"><tr>{groupSpans(shownCols).map(x=><th key={x.group} colSpan={x.span} className="bg-slate-800 text-white border-r border-slate-600 p-2 text-center whitespace-nowrap">{x.group}</th>)}</tr><tr>{shownCols.map(c=><th key={c.key} title={`${c.description}\nSource: ${c.source}`} onClick={e=>sort(c.key,e.shiftKey)} style={{width:widths[c.key]||160,minWidth:widths[c.key]||160,left:stickyLeft(c.key,shownCols,widths)}} className={`${pad} bg-slate-100 border-b border-r text-left whitespace-nowrap cursor-pointer ${c.key==="ticker"||c.key==="company"?"sticky z-40":""}`}>{c.label}{sorts.findIndex(s=>s.key===c.key)>=0?` ${sorts.findIndex(s=>s.key===c.key)+1}${sorts.find(s=>s.key===c.key)?.dir==="asc"?"↑":"↓"}`:""}<span className="float-right cursor-col-resize px-1" onMouseDown={e=>{e.stopPropagation();const start=e.clientX,w=widths[c.key]||160;const move=(m:MouseEvent)=>setWidths(p=>({...p,[c.key]:Math.max(80,w+m.clientX-start)}));const up=()=>{window.removeEventListener("mousemove",move);window.removeEventListener("mouseup",up)};window.addEventListener("mousemove",move);window.addEventListener("mouseup",up)}}>⋮</span></th>)}</tr></thead><tbody>{paged.map(r=><tr key={r.ticker} className="hover:bg-blue-50"><td className="hidden"><input type="checkbox"/></td>{shownCols.map(c=>{const v=r[c.key],sticky=c.key==="ticker"||c.key==="company";return <td key={c.key} style={{left:stickyLeft(c.key,shownCols,widths),maxWidth:widths[c.key]||160}} className={`${pad} border-b border-r bg-white ${sticky?"sticky z-20":""} ${c.format==="longtext"?"truncate":"whitespace-nowrap"}`} title={c.key==="compounderScore"?String(r.scoreDetail||""):display(v,c,r)}>{c.key==="ticker"&&<input className="mr-2" type="checkbox" checked={selected.has(r.ticker)} onChange={()=>setSelected(p=>{const n=new Set(p);n.has(r.ticker)?n.delete(r.ticker):n.add(r.ticker);return n})}/>} {c.editable?<Editable value={v} column={c} onChange={x=>c.format==="longtext"?setEditor({ticker:r.ticker,column:c,value:String(v||"")}):edit(r.ticker,c.key,x)}/>:display(v,c,r)}{c.key==="compounderScore"&&r.scoreComplete===false?<span className="text-amber-600 ml-1" title={String(r.scoreDetail)}>◐</span>:null}</td>})}</tr>)}</tbody></table></div>
    <div className="flex justify-between items-center"><span className="text-xs text-gray-500">Page {page} of {pages}</span><div className="flex gap-2"><button className="btn btn-ghost" disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="btn btn-ghost" disabled={page>=pages} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>
    {editor&&<div className="fixed inset-0 z-[70] bg-black/40 flex items-center justify-center p-4"><div className="bg-white rounded-xl p-4 w-full max-w-2xl"><h3 className="font-semibold mb-2">{editor.ticker} — {editor.column.label}</h3><textarea autoFocus className="input w-full min-h-56" value={editor.value} onChange={e=>setEditor({...editor,value:e.target.value})}/><div className="flex justify-end gap-2 mt-3"><button className="btn btn-ghost" onClick={()=>setEditor(null)}>Cancel</button><button className="btn btn-primary" onClick={()=>{edit(editor.ticker,editor.column.key,editor.value);setEditor(null)}}>Save</button></div></div></div>}
  </div>;
}

function Editable({value,column,onChange}:{value:Cell;column:LongTermColumn;onChange:(v:Cell)=>void}){if(column.format==="longtext")return <button className="text-blue-600 underline" onClick={()=>onChange(value)}>{value?"Edit":"Add"}</button>;if(column.options)return <select className="bg-transparent min-w-28" value={value==null?"":String(value)} onChange={e=>onChange(e.target.value||null)}><option value="">N/A</option>{column.options.map(x=><option key={x}>{x}</option>)}</select>;const numeric=["percent","multiple","currency","number","score"].includes(column.format);return <input className="bg-transparent border-b border-dashed w-28" type={numeric?"number":column.format==="date"?"date":"text"} step="any" value={value==null?"":String(value)} placeholder="N/A" onChange={e=>onChange(numeric?(e.target.value===""?null:Number(e.target.value)):e.target.value)}/>}
function num(v:Cell){const n=Number(v);return v==null||v===""||!Number.isFinite(n)?null:n}
function compare(a:Cell,b:Cell){if(a==null&&b==null)return 0;if(a==null)return 1;if(b==null)return-1;return typeof a==="number"&&typeof b==="number"?a-b:String(a).localeCompare(String(b))}
function suggest(r:Row){const score=num(r.compounderScore),er=num(r.expectedReturn5y),mos=num(r.marginOfSafety);if(score==null||er==null)return "Watchlist";if(score<45)return "Quality Concerns";if(er>=.15&&(mos==null||mos>=0))return "Attractive Now";if(er>=.1)return "Accumulate Gradually";if(er<.05)return "Too Expensive";return "Watchlist"}
function groupSpans(cols:LongTermColumn[]){const out:{group:string;span:number}[]=[];for(const c of cols){const last=out.at(-1);last?.group===c.group?last.span++:out.push({group:c.group,span:1})}return out}
function stickyLeft(key:string,cols:LongTermColumn[],widths:Record<string,number>){if(key==="ticker")return 0;if(key==="company"){const ticker=cols.find(c=>c.key==="ticker");return ticker?(widths.ticker||160):0}return undefined}
